# Generated by Django 2.1.10 on 2019-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ibu', models.IntegerField(default=55)),
                ('calories', models.FloatField(default=0, max_length=5)),
                ('abv', models.FloatField(default=0, max_length=3)),
                ('style', models.CharField(default='Bitter', max_length=50)),
                ('brewery_location', models.CharField(default='Some Brewery', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
